const GET_GAMES = "GET_GAMES";
const ADD_GAME = "ADD_GAME";
const LOGIN = "LOGIN";
const ADD_COUNTER = "ADD_COUNTER";
const AUTHENTICATE = "AUTHENTICATE";
const START_TIME = "START_TIME"
const EXPIRES_CHANGE = "EXPIRES_CHANGE"
const INITIALIZE_USER = "INITIALIZE_USER"

export {
    GET_GAMES,
    ADD_GAME,
    LOGIN,
    ADD_COUNTER,
    AUTHENTICATE,
    START_TIME,
    EXPIRES_CHANGE,
    INITIALIZE_USER
}

